import Foundation
import CryptoKit

//  ShamirTests.swift
//  Seal
//
//  Vectors generated by tools/shamir_vectors.py, an independent Python
//  implementation of the same field. If these pass, the Swift and the Python
//  agree byte for byte on splitting, combining and commitments, and the
//  Python is what tools/verify_capsule.py uses.

enum ShamirTests {

    static let suites: [SelfTest.Suite] = [
        .init(name: "shamir.field", run: field),
        .init(name: "shamir.vectors", run: vectors),
        .init(name: "shamir.random", run: randomRoundTrip),
    ]

    static func hex(_ s: String) -> Data {
        var out = Data(); var i = s.startIndex
        while i < s.endIndex {
            let j = s.index(i, offsetBy: 2)
            out.append(UInt8(s[i..<j], radix: 16)!)
            i = j
        }
        return out
    }

    static func field(_ t: SelfTest.Context) throws {
        // (a, b, a*b) in GF(2^8) with 0x11B. 0x53 * 0xCA = 1 is the AES
        // textbook inverse pair.
        let mul: [(UInt8, UInt8, UInt8)] = [(0x53, 0xCA, 1), (0x02, 0x80, 27), (0xFF, 0xFF, 19),
                                            (0x01, 0x7B, 123), (0x00, 0x9C, 0), (0x1B, 0x1B, 94)]
        for (a, b, c) in mul {
            t.equal(Shamir.mul(a, b), c, "mul \(a)*\(b)")
            t.equal(Shamir.mul(b, a), c, "mul commutes \(a)*\(b)")
        }
        let inv: [(UInt8, UInt8)] = [(1, 1), (2, 141), (3, 246), (0x53, 202), (0xFF, 28), (0x80, 131)]
        for (a, b) in inv {
            t.equal(Shamir.inverse(a), b, "inverse of \(a)")
            t.equal(Shamir.mul(a, Shamir.inverse(a)), 1, "a * a^-1 == 1 for \(a)")
        }
        // Every non-zero element has an inverse and it round-trips.
        for a in 1...255 {
            let x = UInt8(a)
            if Shamir.mul(x, Shamir.inverse(x)) != 1 { t.fail("inverse round trip failed at \(a)"); break }
        }
        t.equal(Shamir.evaluate([5, 0, 0], at: 9), 5, "constant polynomial evaluates to its constant")
        t.equal(Shamir.evaluate([0, 1], at: 0x37), 0x37, "f(x) = x")
    }

    static func vectors(_ t: SelfTest.Context) throws {
        let secret = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let coeffs = ["a54d", "ca18", "2530", "bb1d", "6d13", "2cde", "d623", "7b2e", "d91e", "3f72", "1fcb",
                      "1971", "1744", "94d6", "493c", "9d5c", "3460", "be31", "201e", "69fe", "daa0", "eee8",
                      "b999", "7f5c", "7c29", "99fd", "afe5", "9325", "3cd6", "54af", "4dfa", "d714"]
            .map { [UInt8](hex($0)) }
        let expected = [
            "01e8d317a57af7f352cf44de635f4f7bce449e2c846e1336344d7d50adf6e6a9dc",
            "027eee881a92083d49d9a435e6294b6c45e3b22a140d5f2d8244e9e6b2113f41fa",
            "03963c9dbcecfac81c1ee9e18e7a091984b73d148377590da1118dac04fbc4f639",
            "041e9fbb1280fa7526ba94723e7ca4dcfa9ae269d5bf8297475502420723480835",
            "05f64daeb4fe0880737dd9a6562fe6a93bce6d5742c584b764006608b1c9b3bff6",
        ].map { hex($0) }
        let commitments = [
            "6786370df2ef528f186cb17c93b0b483b3c4e01a534a6a71a048e18a879ac0ee",
            "7e676299fb4b4714ac5333103098ac56daaa57988831d4764148d2013aae929b",
            "ff57c24fe8363481052595c5b79ccf6b111e2945fe317720ae26a9542f0dae79",
            "fe6f6f1d4a59bd555cd8b30fd33a17bdfd83528b83be5a4ed9a582d5f14550ab",
            "fcb86a99e471756dad9b8b91e4771b5f3b17184d4c16b8f6e6ca3b05c5e03e77",
        ]
        let shares = try Shamir.split(secret: secret, threshold: 3, shares: 5, coefficients: coeffs)
        t.equal(shares.count, 5, "five shares")
        for (i, share) in shares.enumerated() {
            t.equal(share.encoded, expected[i], "share \(i + 1) matches the Python vector")
            t.equal(share.commitment.hexString, commitments[i], "commitment \(i + 1) matches")
        }
        t.equal(Data(SHA256.hash(data: secret)).hexString,
                "630dcd2966c4336691125448bbb25b4ff412a49c732db2c8abc1b8581bd710dd", "secret commitment")
        // Combine from the PYTHON share bytes, not our own, so the two
        // implementations are checked against each other in both directions.
        let fromPython = expected.compactMap { Shamir.Share(encoded: $0) }
        t.equal(try Shamir.combine(Array(fromPython.prefix(3)), threshold: 3), secret, "first three recover")
        t.equal(try Shamir.combine([fromPython[0], fromPython[2], fromPython[4]], threshold: 3), secret, "1,3,5 recover")
        t.equal(try Shamir.combine([fromPython[4], fromPython[3], fromPython[1]], threshold: 3), secret, "order does not matter")
        t.throwsError("two shares of three are refused") { _ = try Shamir.combine(Array(fromPython.prefix(2)), threshold: 3) }
        t.throwsError("duplicate index is refused") { _ = try Shamir.combine([fromPython[0], fromPython[1], fromPython[1]], threshold: 3) }

        // 2 of 3 vector
        let secret2 = hex("f0f668bf610e5cf9f11d2aa50f924ada10797100e8f05de085842ddb6370a867")
        let coeffs2 = ["27", "a0", "ae", "b3", "fe", "e9", "23", "2f", "8a", "f2", "21", "1f", "9e", "e4", "91",
                       "c5", "b1", "0b", "ec", "b5", "56", "3b", "fc", "1e", "6f", "93", "42", "7e", "cb", "c8",
                       "fe", "29"].map { [UInt8](hex($0)) }
        let expected2 = [
            "01d756c60c9fe77fd67bef0bba9176db1fa1729db5becba1feea176fa5a8b8564e",
            "02bead2fc286c71aa7fee2689b2841734b696fb2714486bedc5bb9a927eefb4f35",
            "03990d8171782e398874104984b6a5e28ed8645ec412bd42c2342aeb592533b11c",
        ].map { hex($0) }
        let shares2 = try Shamir.split(secret: secret2, threshold: 2, shares: 3, coefficients: coeffs2)
        for (i, share) in shares2.enumerated() {
            t.equal(share.encoded, expected2[i], "2-of-3 share \(i + 1) matches")
        }
        let p2 = expected2.compactMap { Shamir.Share(encoded: $0) }
        t.equal(try Shamir.combine([p2[1], p2[2]], threshold: 2), secret2, "2 of 3 recovers")
    }

    static func randomRoundTrip(_ t: SelfTest.Context) throws {
        for (m, n) in [(1, 1), (1, 3), (2, 2), (2, 3), (3, 5), (5, 7), (7, 10)] {
            let secret = EstateCrypto.randomKey()
            let shares = try Shamir.split(secret: secret, threshold: m, shares: n)
            t.equal(shares.count, n, "\(m)-of-\(n): n shares")
            let subset = Array(shares.shuffled().prefix(m))
            t.equal(try Shamir.combine(subset, threshold: m), secret, "\(m)-of-\(n): any m recover")
            if m > 1 {
                // m-1 shares combined as if the threshold were m-1 must NOT
                // give the secret (they give some other point).
                let fewer = Array(shares.prefix(m - 1))
                let wrong = try Shamir.combine(fewer, threshold: m - 1)
                t.check(wrong != secret, "\(m)-of-\(n): m-1 shares do not recover")
            }
        }
        t.throwsError("threshold above share count is refused") { _ = try Shamir.split(secret: Data([1]), threshold: 3, shares: 2) }
        t.throwsError("empty secret is refused") { _ = try Shamir.split(secret: Data(), threshold: 1, shares: 1) }
        t.check(Shamir.Share(encoded: Data([0, 1, 2])) == nil, "index zero never decodes")
    }
}
