#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""Writes docs/TESTS.md: every test in the app, by name, from the source.

Seal has no test target, because a passkey needs a real app to live in, so
the tests live in `Seal/SelfTest/` and run on every DEBUG launch. That makes
them easy to miss from outside. This lists them, and continuous integration
runs it with --check, so the list can never quietly fall behind the code.

    python3 tools/list_tests.py            # rewrite docs/TESTS.md
    python3 tools/list_tests.py --check    # fail if it is out of date
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SUITES = os.path.join(ROOT, "Seal", "SelfTest")
OUT = os.path.join(ROOT, "docs", "TESTS.md")

NAME = re.compile(r'\.init\(name:\s*"([^"]+)"')
REGISTERED = re.compile(r"\+\s*([A-Za-z0-9_]+)\.suites")


def collect():
    groups = {}
    for name in sorted(os.listdir(SUITES)):
        if not name.endswith("Tests.swift"):
            continue
        with open(os.path.join(SUITES, name), encoding="utf-8") as handle:
            found = NAME.findall(handle.read())
        if found:
            groups[name] = found
    return groups


def registered():
    path = os.path.join(SUITES, "SelfTestRegistry.swift")
    with open(path, encoding="utf-8") as handle:
        text = handle.read()
    names = set(REGISTERED.findall(text))
    first = re.search(r"suites:\s*\[?\s*\n?\s*([A-Za-z0-9_]+)\.suites", text)
    if first:
        names.add(first.group(1))
    return names


def render(groups, live):
    total = sum(len(v) for v in groups.values())
    lines = [
        "# Every test in Seal",
        "",
        "Generated by `tools/list_tests.py` from the source, and checked in",
        "continuous integration, so this page cannot fall behind the code.",
        "",
        "The tests live in the app target under `Seal/SelfTest/` because there",
        "is no test host for a passkey. They run on every DEBUG launch. A",
        "failure blacks the screen on purpose and names the suite. The debug",
        "Time Travel screen runs them again on demand.",
        "",
        f"**{total} tests in {len(groups)} suites.**",
        "",
    ]
    for file, names in groups.items():
        suite = file[: -len(".swift")]
        mark = "" if suite in live else "  (not registered, so it does not run)"
        lines.append(f"## {suite}{mark}")
        lines.append("")
        for name in names:
            lines.append(f"- `{name}`")
        lines.append("")
    return "\n".join(lines)


def main():
    groups = collect()
    text = render(groups, registered())
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            print("docs/TESTS.md is out of date. Run: python3 tools/list_tests.py")
            return 1
        print(f"docs/TESTS.md is current: {sum(len(v) for v in groups.values())} tests")
        return 0
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(text)
    print(f"wrote docs/TESTS.md: {sum(len(v) for v in groups.values())} tests in {len(groups)} suites")
    return 0


if __name__ == "__main__":
    sys.exit(main())
